name: eqs-magnetic-dual-layer
channels:
  - conda-forge
  - defaults
dependencies:
  # Should be on every project
  - python==3.10.*
  - pip
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - black
  # For building latex documents
  - make
  - tectonic
  # Project specific dependencies
  - pandas
  - xarray
  - netcdf4
  - pygmt
  - pyproj
  # Fatiando
  - pooch
  - verde
  - harmonica
  - choclo
